package security;

import java.util.Arrays;

import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;

/**
 * 
 * Class to generate and verify hashes
 * 
 */
public class Hasher {

    private static final int ITERATIONS = 60000;
    private static final int KEY_LENGTH = 256;

    /**
     * 
     * Method that creates a hash given a password and a salt
     * 
     * @param password to hash
     * @param salt which contains salt's bytes
     * 
     * @throws RuntimeException if {@code password} or {@code salt} are null
     * 
     * @return generated hash
     */
    public static byte[] hash(String password, Salt salt) {

        try {
            PBEKeySpec spec = new PBEKeySpec(
                password.toCharArray(), 
                salt.getValue(), 
                ITERATIONS, 
                KEY_LENGTH
            );
            
            SecretKeyFactory factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");

            return factory.generateSecret(spec).getEncoded();

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * 
     * Method that verifies wether {@code password} matches with a hash generated by using the same salt
     *  
     * @param password to verify
     * @param salt used to generate a new hash
     * @param expectedHash hash to compare with
     * 
     * @return True if {@code password} and {@code salt} generate the same hash as {@code expectedHash} <p>
     *         False in other case
     */
    public static boolean verify(String password, Salt salt, byte[] expectedHash) {

        byte[] hash = hash(password, salt);

        return Arrays.equals(hash, expectedHash);
    }
}